version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

  pre_build:
    commands:
      - npm install

  build:
    commands:
      # Not sure how to get staticpkg to tell me what it's hash is, so we'll do it this way.
      - DEPLOY_HASH="$(git rev-parse HEAD)"
      # https://makecode.com/cli/staticpkg
      - node node_modules/pxt-core/built/pxt.js staticpkg -m -r "$DEPLOY_HASH"
      # staticpkg seems to get confused about some things - should fix upstream
      # (also docs have broken /cdn location)
      - cd "built/packaged/$DEPLOY_HASH" && ln -s docs/static
      # It might be cute to put the following in post_build, but unfortunately you have
      # to check for a successful build in that case... (CODEBUILD_BUILD_SUCCEEDING)
      - BRANCH="$(git branch -a --contains HEAD | grep -vF -e '(no branch)' -e 'origin' | head -1 | sed 's/^..//')"
      - echo On branch "$BRANCH"...
      - if [ "$BRANCH" = develop -o "$BRANCH" = master ]; then deploy=true; else deploy=false; fi
      - if $deploy; then aws s3 sync built/packaged/$DEPLOY_HASH "s3://$S3_BUCKET_NAME/$DEPLOY_HASH"; fi
      - if $deploy; then aws s3api put-object --bucket "$S3_BUCKET_NAME" --key index.html --website-redirect-location "/$DEPLOY_HASH/index.html?controller=1"; fi
      - if $deploy; then aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths /index.html; fi

# If you have local_cache on, it seems to do some symlink-y stuff here, and tsc seems to get grumpy
# about that (hypothesis).
#cache:
#  paths:
#    - node_modules/**/*
