name: pxt-testghpkgs

on:
  workflow_dispatch:
    inputs:
        branch-or-commit:
          description: Branch or commit to checkout for test
          required: false
          default: 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch-or-commit }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          sudo npm install -g pxt
          npm install
      - name: pxt buildtarget
        run: pxt buildtarget
      - name: cache build output
        uses: actions/cache@v4
        env:
          cache-name: cache-testghpkgs
        with:
          path: temp/ghpkgs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-       
      - name: pxt testghpkgs
        run: pxt testghpkgs
        env:
          PXT_FORCE_GITHUB_PROXY: 1
          PXT_ACCESS_TOKEN: ${{ secrets.PXT_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload build log
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: logs
          path: temp/ghpkgs/*.txt
